---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhbk-operator
  namespace: rhbk
  labels:
    operators.coreos.com/rhbk-operator.rhbk: ''
  annotations:
    operators.operatorframework.io.display-name: Red Hat build of Keycloak Operator
spec:
  channel: stable-v26.2
  installPlanApproval: Automatic
  name: rhbk-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhbk-operator.v26.2.8-opr.1
...
