---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgres-pvc
  namespace: rhbk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgres
  namespace: rhbk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgres
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: password
      #     volumeMounts:
      #       - name: postgres-storage
      #         mountPath: /data
      #         subPath: postgres-data
      # volumes:
      #   - name: postgres-storage
      #     persistentVolumeClaim:
      #       claimName: keycloak-postgres-pvc
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: rhbk
type: Opaque
data:
  password: YXZlcnlzZWN1cmVwYXNzd29yZA==
  username: a2V5Y2xvYWs=
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
  namespace: rhbk
spec:
  selector:
    app: keycloak-postgres
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
...
